name: CI

on:
  push:
    branches: [ main ]
  pull_request: {}   # run on all PRs
  workflow_dispatch: {}

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive  # needed for bats-support/assert

      - name: Install tools
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            brew update
            brew install shellcheck shfmt
          else
            sudo apt-get update
            sudo apt-get install -y shellcheck shfmt
          fi

      - name: Lint
        run: make lint

      - name: Test
        run: make test
