name: ci
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run bats tests
        run: |
          test/vendor/bats/bin/bats -r test
